#!/bin/sh

set -e

sudo echo "$ nixfmt flake.nix" lib/*.nix
nixfmt flake.nix lib/*.nix
echo

echo "$ sudo nixos-rebuild switch --flake . --impure $@"
sudo nixos-rebuild switch --flake . --impure "$@"
