#!/bin/sh

set -e

sudo echo "$ nixfmt configuration.nix"
nixfmt configuration.nix
echo

echo "$ sudo cp configuration.nix /etc/nixos/"
sudo cp configuration.nix /etc/nixos/
echo

echo "$ sudo nixos-rebuild switch $@"
sudo nixos-rebuild switch "$@"
