[[row]]
[[row.child]]
ratio = 3
[[row.child.child]]
ratio = 5
type = "battery"
[[row.child.child]]
ratio = 4
type = "disk"
[[row.child]]
ratio = 4
type = "mem"
[[row.child]]
ratio = 4
type = "net"

[[row]]
[[row.child]]
ratio = 1
type = "temp"
[[row.child]]
ratio = 5
type = "cpu"

[[row]]
[[row.child]]
ratio = 1
type = "proc"
default = true
