default: update

alias c := clean
clean:
    sudo vkpurge rm all
    sudo xbps-remove -Ooy

alias m := music
music:
    alacritty -e mpv --shuffle --loop-playlist ~/music

sv service:
    sudo ln -st /var/service/ /etc/sv/{{service}} 

alias u := update
update:
    sudo xbps-install -Suy
    rustup update
    cargo install-update -a
