default: update

alias c := clean
clean:
    sudo vkpurge rm all
    sudo xbps-remove -Ooy
    flatpak uninstall --unused -y
    nix-collect-garbage -d

sv service:
    sudo ln -st /var/service/ /etc/sv/{{service}} 

alias u := update
update:
    sudo xbps-install -Suy
    flatpak update -y
    nix-channel --update
    nix-env -u
    rustup update
    cargo install-update -a
