{ pkgs }:

{
  all.start = with pkgs.vimPlugins; [
    bufferline-nvim
    cmp-buffer
    cmp-cmdline
    cmp-dap
    cmp-nvim-lsp
    cmp-path
    cmp_luasnip
    comment-nvim
    crates-nvim
    flatten-nvim
    gitsigns-nvim
    leap-nvim
    lspkind-nvim
    lualine-nvim
    luasnip
    neo-tree-nvim
    nix-develop-nvim
    noice-nvim
    none-ls-nvim
    nvim-cmp
    nvim-colorizer-lua
    nvim-dap
    nvim-dap-ui
    nvim-lspconfig
    nvim-treesitter-textobjects
    nvim-treesitter.withAllGrammars
    nvim-web-devicons
    nvim_context_vt
    rustaceanvim
    snacks-nvim
    telescope-fzf-native-nvim
    telescope-nvim
    trouble-nvim
    typst-preview-nvim
    vim-visual-multi
  ];
}
